### ISSUE TITLE
IE8 IE11下载 选择单图(uploadimage)上传 会提示下载文件

### ISSUE THREAD

**Issue by SvenZhao** [netpi/ueditor#13]
IE下 单图上传 按照示例

    if (req.query.action === 'uploadimage') {
        // var foo = req.ueditor;
        // var date = new Date();
        // var imgname = req.ueditor.filename;
        var img_url = '/img/ueditor/';
        res.ue_up(img_url); //你只要输入要保存的地址 。保存操作交给ueditor来做
    }

会提示下载json文件 
需要在加入一句  res.setHeader('Content-Type', 'text/html');

来解释响应头

**Comment by netpi** [comment]
OK thx 方便的的话提PR

**Comment by netpi** [comment]
已解决
