### ISSUE TITLE
快速多次上传 会出现报错  是流没有监听关闭

### ISSUE THREAD

**Issue by SvenZhao** [netpi/ueditor#16]
修改如下 index.js 74行 流没有监听 关闭结束 就返回json了
>                     var tmp=fs.createWriteStream(tmpdir)
                    file.pipe(tmp);
                    tmp.on('close',function () {
                        fse.move(tmpdir, dest, function (err) {
                            if (err) throw err;
                            res.json({
                                'url': path.join(img_url, name),
                                'title': req.body.pictitle,
                                'original': filename,
                                'state': 'SUCCESS'
                            });
                        });
                    })
>

**Comment by netpi** [comment]
嗯 可以提pr么

**Comment by netpi** [comment]
该问题参考 #8
