### ISSUE TITLE
windows下图片上传后路径不正确bug修复

### ISSUE THREAD

**Issue by tomatojacky** [netpi/ueditor#18]
windows下图片上传后路径“\web\images\ueditor\752116828301561856.jpg” 为反斜杠
我调整了下代码，做了转义，修复了这个 bug
line79  'url': path.join(img_url, name).replace(/\\/g,'/'),

**Comment by netpi** [comment]
@tomatojacky 是否可以提pr修复该问题

**Comment by netpi** [comment]
@tomatojacky 
 `'\'` 需要转义 `replace(/\\/g,'/')` 已提交

**Comment by tomatojacky** [comment]
恩 ，Good Job   前几天忙，没有看到邮件 ，

**Comment by tomatojacky** [comment]
不好意思，才看到邮件。你bug已经修复了就好



--
When the world turns its back on you, you turn your back on the world.

在 2016-07-12 00:35:37，Eury <notifications@github.com> 写道：


@tomatojacky 是否可以提pr修复该问题
