### ISSUE TITLE
你好，请问我附件上传成功了，但是在编辑器内却显示空白是怎么回事

### ISSUE THREAD

**Issue by wacxt** [netpi/ueditor#20]
![image](https://cloud.githubusercontent.com/assets/17725632/19627287/5515bd12-9976-11e6-8fc9-f17f7dbc69cd.png)
![image](https://cloud.githubusercontent.com/assets/17725632/19627293/6eecdc84-9976-11e6-94b0-43bc3e98c130.png)
情况如上述所示，如果你能指导一下，将十分感激。

**Comment by LiGuiRong** [comment]
请问你附件上传代码是如何实现的啊？我图片上传可以实现，但是附件上传不了？

**Comment by LiGuiRong** [comment]
@wacxt 请问你附件上传代码是如何实现的啊，我图片上传可以，但是附件上传一直显示服务器错误

**Comment by SvenZhao** [comment]
@LiGuiRong 看我最新的提交

**Comment by MurphyZhangFC** [comment]
我也碰到了附件上传后编辑区域一片空白的问题，有解决方案吗

**Comment by cashely** [comment]
这个问题确实是需要解决一下的
```javascript
//  客户端发起图片列表请求
    else if (req.query.action === 'listimage') {
        var dir_url = '/uploads/img/';
        console.log(res.ue_list);
        res.ue_list(dir_url); // 客户端会列出 dir_url 目录下的所有图片
    }
    // 客户端发起其它请求
    else {
```
这里没有判断listfile的情况，但是加上listfile判断又会报错说res.ue_list这个方法找不到
