### ISSUE TITLE
hi,什么时候文件上传可以支持云上传呢，谢谢

### ISSUE THREAD

**Issue by harveyff** [netpi/ueditor#26]
比如七牛什么的，谢谢:-D

**Comment by SvenZhao** [comment]
@harveyff  这个应该是在js层面设置的 post的时候 地址改成七牛的上传方式 不需要nodejs支持

**Comment by netpi** [comment]
@SvenZhao thank you

**Comment by netpi** [comment]
@harveyff server端

**Comment by netpi** [comment]
server端可以配置  https://github.com/netpi/ueditor/blob/master/lib/index.js#L67 在这部分之后处理下上传 有人愿意pr么

**Comment by 310676645** [comment]
@netpi 已提交pr

**Comment by netpi** [comment]
@310676645 好的 我来check 下
