### ISSUE TITLE
只支持express吗？

### ISSUE THREAD

**Issue by johnhjwsosd** [netpi/ueditor#27]
我用koa  来添加中间件时会出现TypeError: middleware must be a function!

**Comment by Net-JetChan** [comment]
我也是，请问你解决了吗 @johnhjwsosd

**Comment by netpi** [comment]
@johnhjwsosd @Net-JetChan 目前是的 谁要是要时间做koa版本 联系我 我开个org

**Comment by cqllang** [comment]
发现一个koa版本 https://github.com/weivea/koa-ueditor
