### ISSUE TITLE
Uncaught SyntaxError: Unexpected token : config.json:4

### ISSUE THREAD

**Issue by LiuC520** [netpi/ueditor#38]
`我用你的例子是可以跑起来的，后端直接拷贝的你的ueditor放到了express的public下面，我前端用的是react，前端的初始化editor配置是有个服务器的配置路径，`serverUrl : http://127.0.0.1:8031/ueditor/ue`，我在浏览器里面输入http://127.0.0.1:8031/ueditor/ue?action=uploadimage，但是返回报错，说你的config.json第4行报错，我就搞不清清楚了

**Comment by 310676645** [comment]
我也遇到了这个问题

**Comment by jindasong** [comment]
已解决，官方默认是用jsonp来解决跨域问题，将ueditor.all文件的下图两处更改一下就可以

![](http://ohhqdafpw.bkt.clouddn.com/note/images/ueditor-config-error)

**Comment by justicezt0711** [comment]
@jindasong  按照你的改了 还是没用 是改前端的文件的ueditor.all吧

**Comment by justicezt0711** [comment]
@jindasong  解决了 原来是引用了all.min文件

**Comment by Guanyuhao** [comment]
mark 原来是跨域！！！

**Comment by MinWest** [comment]
> @LiuC520
> 已解决，官方默认是用jsonp来解决跨域问题，将ueditor.all文件的下图两处更改一下就可以
> 
> ![](https://camo.githubusercontent.com/d13ac95ca2b60a880b1697447321c691dcf9df97/687474703a2f2f6f68687164616670772e626b742e636c6f7564646e2e636f6d2f6e6f74652f696d616765732f75656469746f722d636f6e6669672d6572726f72)

没图了
