### ISSUE TITLE
关于配置的问题来这里提

### ISSUE THREAD

**Issue by netpi** [netpi/ueditor#4]

**Comment by yeagle2468** [comment]
“npm WARN install Refusing to install ueditor as a dependency of itself”, can't install ueditor

**Comment by netpi** [comment]
@yeagle2468 你在ueditor包中又安装了了ueditor 循环安装了...

**Comment by webbought** [comment]
'ue_up '这个方法的fse.move()应该要在file触发了end事件后才执行吧?

**Comment by julor** [comment]
res.redirect('/ueditor/ueditor.config.json')，这是哪个文件，找不到

**Comment by netpi** [comment]
@julor 是这个文件 [https://github.com/netpi/ueditor/blob/master/example/public/ueditor/ueditor.config.js](https://github.com/netpi/ueditor/blob/master/example/public/ueditor/ueditor.config.js)

**Comment by netpi** [comment]
@julor  [https://github.com/netpi/ueditor/blob/master/example/public/ueditor/nodejs/config.json](https://github.com/netpi/ueditor/blob/master/example/public/ueditor/nodejs/config.json) 在这里

**Comment by julor** [comment]
谢谢

**Comment by HelloCui** [comment]
![image](https://cloud.githubusercontent.com/assets/4626117/8668970/0e196a74-2a43-11e5-9472-749e14a81be9.png)

**Comment by netpi** [comment]
@HelloCui  客户端ueditor版本，express版本说下

**Comment by zhougch5** [comment]
我想问的就是，为什么我在ueditor编辑框里面去掉图片的时候，原来的的图片没有删除掉，如果我想在去掉编辑框里面的同时想删掉对应的图片，我应该怎么做？

**Comment by la413972057** [comment]
想请问一下，我的图片上传功能是实现了，但是多图上传的在线管理一直都是不行的，找了很久也没发现错在哪儿，控制台提示是GET /ueditor/ue?action=listimage&start=0&size=20&noCache=1445179933504 500 2.067 ms - 1003
是不是我的配置哪里没有对呢？望答复，谢谢
