### ISSUE TITLE
不支持 附件上传 和 附件在线 

### ISSUE THREAD

**Issue by euro951** [netpi/ueditor#40]
![image](https://cloud.githubusercontent.com/assets/10275965/25476713/aa9dc46c-2b6d-11e7-8e30-ce7546d7f50c.png)
action是 listfile 
没有判断。

**Comment by euro951** [comment]
![image](https://cloud.githubusercontent.com/assets/10275965/25600522/4676c3b4-2f17-11e7-9c21-17658856095a.png)
简单的实现附件上传  加在ueditor.all.js

**Comment by netpi** [comment]
@euro951 欢迎 pr

**Comment by HelloJasonZhang** [comment]
在ueditor.all.js里面添加如下代码：

UE.commands['insertfile'] = {
    execCommand: function (cmd, opt){
        opt = utils.isArray(opt) ? opt: [opt];
        if(!opt.length){
            return;
        }
        var me = this,
            range = me.selection.getRange(),
            img = range.getClosedNode();

        var htmlStr = [];
        var temp = "";
        var i = 0;
        for (var i = 0; i < opt.length; i++) {
            var element = opt[i];
            temp = '<p style="line-height: 16px;"><a style="font-size:12px;color:#0066cc;" href="'+element.url+'">'+element.title+'</a></p>';
            console.log(temp)
            htmlStr.push(temp)
        }
        me.execCommand('insertHtml', htmlStr.join(""))
    }
};
