### ISSUE TITLE
vue 和 node 跨域 拿到了config.json 但是 Unexpected token :

### ISSUE THREAD

**Issue by justicezt0711** [netpi/ueditor#58]
在node环境下 使用demo是可以上传的  但是前端 和后端域名不同情况下 访问serverUrl 能获取到json文件 但是会出现Unexpected token : 感觉是跨域问题 招了很多没解决 求

**Comment by zhuzhengjing** [comment]
> 在node环境下 使用demo是可以上传的 但是前端 和后端域名不同情况下 访问serverUrl 能获取到json文件 但是会出现Unexpected token : 感觉是跨域问题 招了很多没解决 求

问题解决了吗？我也遇到相同的问题。
