### ISSUE TITLE
nodejs使用的时候上传第二张图片报错说找不到临时文件

### ISSUE THREAD

**Issue by chua1989** [netpi/ueditor#8]
项目还没有部署到网上去，用的本地作为服务器。
上传第一张的时候没有问题。上传第二张的时候就会报错。使用chrome查看最后一个传递到服务端的请求提示为“Provisional headers are shown”,意味着请求根本就没有发出去。

而nodejs后台已经挂了提示node_modules\ueditor\index.js:77 
  if(err) throw err;

Error:ENOENT: no such file or directory, link 'C:\Users\ADMINI~1\AppData\Local\Temp\Desert.jpg' -> 'F:\chuaNodejs\chuayyqing\static\images\ueditor\705214004658163712.jpg'
  at Error (native)

**Comment by netpi** [comment]
@chua1989 第二张和第一张是相同的图片么

**Comment by chua1989** [comment]
不是，我快速上传就会出现这个问题

**Comment by lizhil** [comment]
我也有这样的问题
![qq 20160320011722](https://cloud.githubusercontent.com/assets/12292949/13900119/908ba1ce-ee39-11e5-8e79-d801feea21a9.png)

**Comment by zhm8932** [comment]
这个问题有解决吗

**Comment by lizhil** [comment]
@zhm8932 

来源 http://blog.netpi.me/nodejs/ueditor-nodejs/ 评论李猛
file.pipe(fs.createWriteStream(tmpdir));
file.on('end', function() { //这行是我添加的，等文件写完后在执行下面的移动超值
    fse.move(tmpdir, dest, function(err) {
        if (err) throw err;
        res.json({
            'url': path.join(img_url, name),
            'title': req.body.pictitle,
            'original': filename,
            'state': 'SUCCESS'
        });
    });
});

**Comment by SvenZhao** [comment]
@zhm8932
                    var tmp=fs.createWriteStream(tmpdir)
                    file.pipe(tmp);
                    tmp.on('close',function () {
                        fse.move(tmpdir, dest, function (err) {
                            if (err) throw err;
                            res.json({
                                'url': path.join(img_url, name),
                                'title': req.body.pictitle,
                                'original': filename,
                                'state': 'SUCCESS'
                            });
                        });
                    })

**Comment by netpi** [comment]
感谢 @SvenZhao  该问题已解决 请升级道1.1.3
