### ISSUE TITLE
图片上传问题

### ISSUE THREAD

**Issue by andrewei1316** [netpi/ueditor#9]
有没有本地图片绝对URL转相对URL的功能啊，好像在说明里没有看到

**Comment by SvenZhao** [comment]
@andrewei1316 
res.ue_up = function (img_url) {
          var tmpdir = path.join(os.tmpDir(), path.basename(filename));
          var name = snowflake.nextId() + path.extname(tmpdir);
          var dest = path.join(static_url, img_url, name);
          var writeStream = fs.createWriteStream(tmpdir);
          file.pipe(writeStream);
          writeStream.on("close", function () {
            fse.move(tmpdir, dest, function (err) {
              if (err) throw err;
              res.json({
                'url': path.join(img_url, name), //debug 修改此处的代码 就可以返回相对路劲了 或者你pr给作者一个配置项把
                'title': req.body.pictitle,
                'original': filename,
                'state': 'SUCCESS'
              });
            });
          })

**Comment by netpi** [comment]
@SvenZhao thank you
